#!/usr/bin/env perl
use strict;
use warnings;

my @FORMS = qw{
    goqolib
    fwvagnt
    fgibdsr
    gzieacc
    gzvzipc
    pzaempl
    rzadetl
    rzavetn
    rzrcreq
    rzvssap
    tzaschd
};

sub scp {
    my ($from, $to) = @_;
    system("scp $from $to");
}

for my $form (@FORMS) {
    scp "banprgm\@jobsubdev:~/links/$form.fmb" => "forms" unless -e "forms/$form.fmb";
}
